# test_and_submit.yml
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # Check CVE records and publish them    
      - name: CVE RSUS check and upload
        uses: DIVD-NL/cve-rsus-validate-submit@v1
        with: 
          cve-user        : ${{ secrets.CVE_USER }}
          cve-org         : ${{ secrets.CVE_ORG }}
          cve-api-key     : ${{ secrets.CVE_API_KEY }}
          cve-environment : test
          publish         : ${{ github.event_name != 'pull_request' }}    # Only publish when we merge into the main branch
          path            : records/                                      # This is where the CVE records live
          ignore          : ""                                            # Don't ignore any checks
          min-reserved    : 10                                            # Keep at least 10 reserved records (for the current year)
          reserve         : 10                                            # Reserve a minimum of 10 records at a time 
          pr              : ${{ github.event_name != 'pull_request' }}
          github-token    : ${{ secrets.GH_TOKEN }}